// <auto-generated />
using ContactAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactAPI.Migrations
{
    [DbContext(typeof(ContactsContext))]
    [Migration("20240902060038_SeedInitialContacts")]
    partial class SeedInitialContacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ContactAPI.Entitties.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryMobileNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            MobileNumber = "1234567890",
                            Name = "John Doe",
                            Photo = "",
                            SecondaryMobileNumber = "0987654321"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@example.com",
                            MobileNumber = "2345678901",
                            Name = "Jane Smith",
                            Photo = "",
                            SecondaryMobileNumber = "1987654321"
                        },
                        new
                        {
                            Id = 3,
                            Email = "michael.johnson@example.com",
                            MobileNumber = "3456789012",
                            Name = "Michael Johnson",
                            Photo = "",
                            SecondaryMobileNumber = "2987654321"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
