// <auto-generated />
using ContactAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactAPI.Migrations
{
    [DbContext(typeof(ContactsContext))]
    [Migration("20240903041743_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ContactAPI.Entitties.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryMobileNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            MobileNumber = "1234567890",
                            Name = "John Doe",
                            Photo = "https://randomuser.me/api/portraits/men/1.jpg",
                            SecondaryMobileNumber = "0987654321"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@example.com",
                            MobileNumber = "2345678901",
                            Name = "Jane Smith",
                            Photo = "https://randomuser.me/api/portraits/women/2.jpg",
                            SecondaryMobileNumber = "1987654321"
                        },
                        new
                        {
                            Id = 3,
                            Email = "michael.johnson@example.com",
                            MobileNumber = "3456789012",
                            Name = "Michael Johnson",
                            Photo = "https://randomuser.me/api/portraits/men/3.jpg",
                            SecondaryMobileNumber = "2987654321"
                        },
                        new
                        {
                            Id = 4,
                            Email = "emily.davis@example.com",
                            MobileNumber = "4567890123",
                            Name = "Emily Davis",
                            Photo = "https://randomuser.me/api/portraits/women/4.jpg",
                            SecondaryMobileNumber = "3987654321"
                        },
                        new
                        {
                            Id = 5,
                            Email = "david.wilson@example.com",
                            MobileNumber = "5678901234",
                            Name = "David Wilson",
                            Photo = "https://randomuser.me/api/portraits/men/5.jpg",
                            SecondaryMobileNumber = "4987654321"
                        },
                        new
                        {
                            Id = 6,
                            Email = "sophia.brown@example.com",
                            MobileNumber = "6789012345",
                            Name = "Sophia Brown",
                            Photo = "https://randomuser.me/api/portraits/women/6.jpg",
                            SecondaryMobileNumber = "5987654321"
                        },
                        new
                        {
                            Id = 7,
                            Email = "james.anderson@example.com",
                            MobileNumber = "7890123456",
                            Name = "James Anderson",
                            Photo = "https://randomuser.me/api/portraits/men/7.jpg",
                            SecondaryMobileNumber = "6987654321"
                        },
                        new
                        {
                            Id = 8,
                            Email = "olivia.martinez@example.com",
                            MobileNumber = "8901234567",
                            Name = "Olivia Martinez",
                            Photo = "https://randomuser.me/api/portraits/women/8.jpg",
                            SecondaryMobileNumber = "7987654321"
                        },
                        new
                        {
                            Id = 9,
                            Email = "benjamin.garcia@example.com",
                            MobileNumber = "9012345678",
                            Name = "Benjamin Garcia",
                            Photo = "https://randomuser.me/api/portraits/men/9.jpg",
                            SecondaryMobileNumber = "8987654321"
                        },
                        new
                        {
                            Id = 10,
                            Email = "charlotte.miller@example.com",
                            MobileNumber = "0123456789",
                            Name = "Charlotte Miller",
                            Photo = "https://randomuser.me/api/portraits/women/10.jpg",
                            SecondaryMobileNumber = "9987654321"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
