// <auto-generated />
using ContactAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactAPI.Migrations
{
    [DbContext(typeof(ContactsContext))]
    [Migration("20240906042347_seedData1")]
    partial class seedData1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ContactAPI.Entitties.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryMobileNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 51,
                            Email = "anjali.sharma51@example.com",
                            MobileNumber = "919923456001",
                            Name = "Anjali Sharma",
                            Photo = "https://randomuser.me/api/portraits/women/51.jpg",
                            SecondaryMobileNumber = "918012345601"
                        },
                        new
                        {
                            Id = 52,
                            Email = "vikram.malhotra52@example.com",
                            MobileNumber = "919923456002",
                            Name = "Vikram Malhotra",
                            Photo = "https://randomuser.me/api/portraits/men/52.jpg",
                            SecondaryMobileNumber = "918012345602"
                        },
                        new
                        {
                            Id = 53,
                            Email = "priya.nair53@example.com",
                            MobileNumber = "919923456003",
                            Name = "Priya Nair",
                            Photo = "https://randomuser.me/api/portraits/women/53.jpg",
                            SecondaryMobileNumber = "918012345603"
                        },
                        new
                        {
                            Id = 54,
                            Email = "rohit.mehta54@example.com",
                            MobileNumber = "919923456004",
                            Name = "Rohit Mehta",
                            Photo = "https://randomuser.me/api/portraits/men/54.jpg",
                            SecondaryMobileNumber = "918012345604"
                        },
                        new
                        {
                            Id = 55,
                            Email = "sana.kapoor55@example.com",
                            MobileNumber = "919923456005",
                            Name = "Sana Kapoor",
                            Photo = "https://randomuser.me/api/portraits/women/55.jpg",
                            SecondaryMobileNumber = "918012345605"
                        },
                        new
                        {
                            Id = 56,
                            Email = "rakesh.iyer56@example.com",
                            MobileNumber = "919923456006",
                            Name = "Rakesh Iyer",
                            Photo = "https://randomuser.me/api/portraits/men/56.jpg",
                            SecondaryMobileNumber = "918012345606"
                        },
                        new
                        {
                            Id = 57,
                            Email = "neha.bhatia57@example.com",
                            MobileNumber = "919923456007",
                            Name = "Neha Bhatia",
                            Photo = "https://randomuser.me/api/portraits/women/57.jpg",
                            SecondaryMobileNumber = "918012345607"
                        },
                        new
                        {
                            Id = 58,
                            Email = "aman.verma58@example.com",
                            MobileNumber = "919923456008",
                            Name = "Aman Verma",
                            Photo = "https://randomuser.me/api/portraits/men/58.jpg",
                            SecondaryMobileNumber = "918012345608"
                        },
                        new
                        {
                            Id = 59,
                            Email = "kavita.shetty59@example.com",
                            MobileNumber = "919923456009",
                            Name = "Kavita Shetty",
                            Photo = "https://randomuser.me/api/portraits/women/59.jpg",
                            SecondaryMobileNumber = "918012345609"
                        },
                        new
                        {
                            Id = 60,
                            Email = "nikhil.jain60@example.com",
                            MobileNumber = "919923456010",
                            Name = "Nikhil Jain",
                            Photo = "https://randomuser.me/api/portraits/men/60.jpg",
                            SecondaryMobileNumber = "918012345610"
                        },
                        new
                        {
                            Id = 61,
                            Email = "divya.reddy61@example.com",
                            MobileNumber = "919923456011",
                            Name = "Divya Reddy",
                            Photo = "https://randomuser.me/api/portraits/women/61.jpg",
                            SecondaryMobileNumber = "918012345611"
                        },
                        new
                        {
                            Id = 62,
                            Email = "manish.gupta62@example.com",
                            MobileNumber = "919923456012",
                            Name = "Manish Gupta",
                            Photo = "https://randomuser.me/api/portraits/men/62.jpg",
                            SecondaryMobileNumber = "918012345612"
                        },
                        new
                        {
                            Id = 63,
                            Email = "pooja.rai63@example.com",
                            MobileNumber = "919923456013",
                            Name = "Pooja Rai",
                            Photo = "https://randomuser.me/api/portraits/women/63.jpg",
                            SecondaryMobileNumber = "918012345613"
                        },
                        new
                        {
                            Id = 64,
                            Email = "saurabh.khanna64@example.com",
                            MobileNumber = "919923456014",
                            Name = "Saurabh Khanna",
                            Photo = "https://randomuser.me/api/portraits/men/64.jpg",
                            SecondaryMobileNumber = "918012345614"
                        },
                        new
                        {
                            Id = 65,
                            Email = "ayesha.khan65@example.com",
                            MobileNumber = "919923456015",
                            Name = "Ayesha Khan",
                            Photo = "https://randomuser.me/api/portraits/women/65.jpg",
                            SecondaryMobileNumber = "918012345615"
                        },
                        new
                        {
                            Id = 66,
                            Email = "rahul.sen66@example.com",
                            MobileNumber = "919923456016",
                            Name = "Rahul Sen",
                            Photo = "https://randomuser.me/api/portraits/men/66.jpg",
                            SecondaryMobileNumber = "918012345616"
                        },
                        new
                        {
                            Id = 67,
                            Email = "megha.dixit67@example.com",
                            MobileNumber = "919923456017",
                            Name = "Megha Dixit",
                            Photo = "https://randomuser.me/api/portraits/women/67.jpg",
                            SecondaryMobileNumber = "918012345617"
                        },
                        new
                        {
                            Id = 68,
                            Email = "ashish.pandey68@example.com",
                            MobileNumber = "919923456018",
                            Name = "Ashish Pandey",
                            Photo = "https://randomuser.me/api/portraits/men/68.jpg",
                            SecondaryMobileNumber = "918012345618"
                        },
                        new
                        {
                            Id = 69,
                            Email = "simran.singh69@example.com",
                            MobileNumber = "919923456019",
                            Name = "Simran Singh",
                            Photo = "https://randomuser.me/api/portraits/women/69.jpg",
                            SecondaryMobileNumber = "918012345619"
                        },
                        new
                        {
                            Id = 70,
                            Email = "ajay.kumar70@example.com",
                            MobileNumber = "919923456020",
                            Name = "Ajay Kumar",
                            Photo = "https://randomuser.me/api/portraits/men/70.jpg",
                            SecondaryMobileNumber = "918012345620"
                        },
                        new
                        {
                            Id = 71,
                            Email = "ritika.chauhan71@example.com",
                            MobileNumber = "919923456021",
                            Name = "Ritika Chauhan",
                            Photo = "https://randomuser.me/api/portraits/women/71.jpg",
                            SecondaryMobileNumber = "918012345621"
                        },
                        new
                        {
                            Id = 72,
                            Email = "siddharth.joshi72@example.com",
                            MobileNumber = "919923456022",
                            Name = "Siddharth Joshi",
                            Photo = "https://randomuser.me/api/portraits/men/72.jpg",
                            SecondaryMobileNumber = "918012345622"
                        },
                        new
                        {
                            Id = 73,
                            Email = "kriti.ahuja73@example.com",
                            MobileNumber = "919923456023",
                            Name = "Kriti Ahuja",
                            Photo = "https://randomuser.me/api/portraits/women/73.jpg",
                            SecondaryMobileNumber = "918012345623"
                        },
                        new
                        {
                            Id = 74,
                            Email = "ravi.thakur74@example.com",
                            MobileNumber = "919923456024",
                            Name = "Ravi Thakur",
                            Photo = "https://randomuser.me/api/portraits/men/74.jpg",
                            SecondaryMobileNumber = "918012345624"
                        },
                        new
                        {
                            Id = 75,
                            Email = "sonia.dutta75@example.com",
                            MobileNumber = "919923456025",
                            Name = "Sonia Dutta",
                            Photo = "https://randomuser.me/api/portraits/women/75.jpg",
                            SecondaryMobileNumber = "918012345625"
                        },
                        new
                        {
                            Id = 76,
                            Email = "arjun.bhatt76@example.com",
                            MobileNumber = "919923456026",
                            Name = "Arjun Bhatt",
                            Photo = "https://randomuser.me/api/portraits/men/76.jpg",
                            SecondaryMobileNumber = "918012345626"
                        },
                        new
                        {
                            Id = 77,
                            Email = "riya.roy77@example.com",
                            MobileNumber = "919923456027",
                            Name = "Riya Roy",
                            Photo = "https://randomuser.me/api/portraits/women/77.jpg",
                            SecondaryMobileNumber = "918012345627"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
